print("Enter four numbers: ")
number_one = int(input())
number_two = int(input())
number_free = int(input())
number_four = int(input())
answer = (number_one + number_two) / (number_free + number_four)
print("%.2f" % answer)