print("Введите четыре числа: ")
number_one = int(input())
number_two = int(input())
number_free = int(input())
number_four = int(input())
sum_one = (number_one + number_two)
sum_two = (number_free + number_four)
answer = (sum_one)/(sum_two)
print("%.2f" % answer)