userName = input("What is your name? ")
userAge = input("How old are you? ")
userHome = input("S(he) live is? ")
print("Your name: ", userName)
print("Your age: ", userAge)
print("You live in: ", userHome)